name: mevacoin-android

on:
  workflow_dispatch:

jobs:
  build-boost:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git unzip cmake ninja-build
          pip install "conan==1.60.2"

      - name: Download Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
          unzip android-ndk-r26d-linux.zip
          mv android-ndk-r26d $HOME/android-ndk

      - name: Cache Conan packages
        uses: actions/cache@v3
        with:
          path: ~/.conan/data
          key: conan-android-boost-1.81.0-${{ runner.os }}-${{ hashFiles('**/conanfile.txt') }}
          restore-keys: |
            conan-android-boost-1.81.0-${{ runner.os }}-

      - name: Create Conan profile (Android arm64-v8a)
        run: |
          mkdir -p ~/.conan/profiles
          echo "[settings]" > ~/.conan/profiles/android_21_arm64_v8a
          echo "os=Android" >> ~/.conan/profiles/android_21_arm64_v8a
          echo "os.api_level=21" >> ~/.conan/profiles/android_21_arm64_v8a
          echo "arch=armv8" >> ~/.conan/profiles/android_21_arm64_v8a
          echo "compiler=clang" >> ~/.conan/profiles/android_21_arm64_v8a
          echo "compiler.version=9" >> ~/.conan/profiles/android_21_arm64_v8a
          echo "compiler.libcxx=libstdc++" >> ~/.conan/profiles/android_21_arm64_v8a
          echo "build_type=Release" >> ~/.conan/profiles/android_21_arm64_v8a
          echo "" >> ~/.conan/profiles/android_21_arm64_v8a
          echo "[env]" >> ~/.conan/profiles/android_21_arm64_v8a
          echo "ANDROID_NDK=$HOME/android-ndk" >> ~/.conan/profiles/android_21_arm64_v8a
          echo "CC=$HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang" >> ~/.conan/profiles/android_21_arm64_v8a
          echo "CXX=$HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++" >> ~/.conan/profiles/android_21_arm64_v8a
          echo "AR=$HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar" >> ~/.conan/profiles/android_21_arm64_v8a
          echo "RANLIB=$HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib" >> ~/.conan/profiles/android_21_arm64_v8a
          echo "" >> ~/.conan/profiles/android_21_arm64_v8a
          echo "[conf]" >> ~/.conan/profiles/android_21_arm64_v8a
          echo "tools.android:ndk_path=$HOME/android-ndk" >> ~/.conan/profiles/android_21_arm64_v8a
          echo "tools.build:cross_building=1" >> ~/.conan/profiles/android_21_arm64_v8a
          echo "tools.gnu:host=aarch64-linux-android" >> ~/.conan/profiles/android_21_arm64_v8a

      - name: Build Boost (and libiconv) for Android
        run: |
          conan install boost/1.81.0@ \
            --profile android_21_arm64_v8a \
            --build=missing \
            -o boost:without_stacktrace=True \
            -o boost:without_python=True

  build-mevacoin:
    runs-on: ubuntu-latest
    needs: build-boost

    steps:
      - name: Checkout Mevacoin repo
        uses: actions/checkout@v4
        with:
          repository: pasqualelembo78/mevacoin
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git unzip cmake ninja-build
          pip install "conan==1.60.2"

      - name: Restore Conan cache
        uses: actions/cache@v3
        with:
          path: ~/.conan/data
          key: conan-android-boost-1.81.0-${{ runner.os }}-${{ hashFiles('**/conanfile.txt') }}
          restore-keys: |
            conan-android-boost-1.81.0-${{ runner.os }}-

      - name: Download Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
          unzip android-ndk-r26d-linux.zip
          mv android-ndk-r26d $HOME/android-ndk

      - name: Build Mevacoin
        run: |
          mkdir -p build/android
          cd build/android
          cmake -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE=$HOME/android-ndk/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-21 \
            -DCMAKE_BUILD_TYPE=Release \
            -DBOOST_ROOT=$HOME/.conan/data/boost/1.81.0/_/_/package \
            -DBOOST_INCLUDEDIR=$HOME/.conan/data/boost/1.81.0/_/_/package/*/include \
            -DBOOST_LIBRARYDIR=$HOME/.conan/data/boost/1.81.0/_/_/package/*/lib \
            ../..
          cmake --build .

      - name: Upload Mevacoin Android binary
        uses: actions/upload-artifact@v4
        with:
          name: mevacoin-android
          path: build/android/mevacoind
