name: mevacoin-android

on:
  workflow_dispatch:

jobs:
  build-boost:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system build tools
        run: |
          sudo apt update
          sudo apt install -y git unzip cmake ninja-build build-essential pkg-config autoconf automake libtool wget
          pip install "conan==1.60.2"

      - name: Download Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
          unzip -q android-ndk-r26d-linux.zip
          mv android-ndk-r26d $HOME/android-ndk
          export PATH=$HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

      - name: Cache Conan packages
        uses: actions/cache@v3
        with:
          path: ~/.conan/data
          key: conan-android-boost-1.81.0-${{ runner.os }}-${{ hashFiles('**/conanfile.txt') }}
          restore-keys: |
            conan-android-boost-1.81.0-${{ runner.os }}-

      - name: Create Conan profile (Android arm64-v8a)
        run: |
          mkdir -p ~/.conan/profiles
          cat > ~/.conan/profiles/android_21_arm64_v8a <<'EOF'
[settings]
os=Android
os.api_level=21
arch=armv8
compiler=clang
compiler.version=9
compiler.libcxx=libstdc++
build_type=Release

[env]
ANDROID_NDK=$HOME/android-ndk
CC=$HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang
CXX=$HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++
AR=$HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar
RANLIB=$HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib

[conf]
tools.android:ndk_path=$HOME/android-ndk
tools.build:cross_building=1
tools.gnu:host=aarch64-linux-android
EOF

      - name: Create local libiconv conan recipe
        run: |
          mkdir -p local_recipes/libiconv
          cat > local_recipes/libiconv/conanfile.py <<'EOF'
from conans import ConanFile, tools
import os

class LibiconvConan(ConanFile):
    name = "libiconv"
    version = "1.17"
    settings = "os", "arch", "compiler", "build_type"
    exports_sources = []
    no_copy_source = False

    def source(self):
        tools.get("https://ftp.gnu.org/gnu/libiconv/libiconv-1.17.tar.gz", strip_root=True)

    def build(self):
        ndk = os.environ.get("ANDROID_NDK")
        if not ndk:
            raise Exception("ANDROID_NDK environment variable not set")
        cc = os.path.join(ndk, "toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang")
        ar = os.path.join(ndk, "toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar")
        ranlib = os.path.join(ndk, "toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib")
        src_dir = os.path.join(self.source_folder, "libiconv-1.17")
        prefix = os.path.join(self.build_folder, "install")
        with tools.chdir(src_dir):
            env = {"CC": cc, "AR": ar, "RANLIB": ranlib}
            args = [
                "./configure",
                "--host=aarch64-linux-android",
                f"--prefix={prefix}",
                "--disable-shared",
                "--enable-static"
            ]
            self.run(" ".join(args), env=env)
            self.run(f"make -j{os.cpu_count() or 2}", env=env)
            self.run("make install", env=env)

    def package(self):
        prefix = os.path.join(self.build_folder, "install")
        if os.path.isdir(prefix):
            self.copy(pattern="*", dst="include", src=os.path.join(prefix, "include"))
            self.copy(pattern="*.a", dst="lib", src=os.path.join(prefix, "lib"))
            self.copy(pattern="*.so*", dst="lib", src=os.path.join(prefix, "lib"), keep_path=False)

    def package_info(self):
        self.cpp_info.libs = ["iconv"]
EOF

      - name: Build and export local libiconv package to Conan cache
        env:
          ANDROID_NDK: $HOME/android-ndk
          CC: $HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang
          CXX: $HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++
          AR: $HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar
          RANLIB: $HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib
        run: |
          conan create local_recipes/libiconv libiconv/1.17@ --profile android_21_arm64_v8a

      - name: Build Boost for Android (using local libiconv)
        run: |
          conan install boost/1.81.0@ \
            --profile android_21_arm64_v8a \
            --build=missing \
            -o boost:i18n_backend=iconv \
            -o boost:i18n_backend_iconv=libiconv \
            -o boost:without_python=True \
            -o boost:without_stacktrace=False

      - name: (Optional) Upload Conan cache artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: conan-cache
          path: ~/.conan/data
