name: Build Boost for Android

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-venv build-essential cmake git unzip

      - name: Install Conan
        run: |
          python3 -m pip install --upgrade pip
          pip install conan

      - name: Setup Android NDK
        uses: android-actions/setup-ndk@v3
        with:
          ndk-version: 25.2.9519653

      - name: Create Conan Android profile
        run: |
          conan profile new android-arm64 --detect || true
          conan profile update settings.os=Android android-arm64
          conan profile update settings.arch=armv8 android-arm64
          conan profile update settings.compiler=clang android-arm64
          conan profile update settings.compiler.version=16 android-arm64
          conan profile update settings.compiler.libcxx=libc++ android-arm64
          conan profile update settings.build_type=Release android-arm64
          conan profile update env.CC=$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang android-arm64
          conan profile update env.CXX=$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ android-arm64

      - name: Install Boost for Android
        run: |
          mkdir -p build
          cd build
          conan install boost/1.81.0@conan/stable -pr android-arm64 --build=missing

      - name: Build Boost
        run: |
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake \
                   -DANDROID_ABI=arm64-v8a \
                   -DANDROID_PLATFORM=android-21 \
                   -DCMAKE_BUILD_TYPE=Release
          cmake --build .
