name: Build Boost for Android (header-only)

on:
  workflow_dispatch:   # Avvio manuale dal tab Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip git unzip cmake ninja-build
          pip install "conan==1.60.2"

      - name: Download Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
          unzip android-ndk-r26d-linux.zip
          mv android-ndk-r26d $HOME/android-ndk

      - name: Create Conan profile (Android arm64-v8a)
        run: |
          mkdir -p ~/.conan/profiles
          cat > ~/.conan/profiles/android_21_arm64_v8a <<EOF
          [settings]
          os=Android
          os.api_level=21
          arch=armv8
          compiler=clang
          compiler.version=9
          compiler.libcxx=libc++
          build_type=Release

          [env]
          ANDROID_NDK=$HOME/android-ndk
          CC=$HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang
          CXX=$HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++
          AR=$HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar
          RANLIB=$HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib
          EOF

      - name: Clone Conan Center Index
        run: |
          git clone https://github.com/conan-io/conan-center-index.git

      - name: Build Boost (header-only)
        run: |
          cd conan-center-index/recipes/boost/all
          conan create . boost/1.81.0@conan/stable \
            --profile android_21_arm64_v8a \
            -o boost:header_only=True

      - name: Upload Conan cache as artifact
        uses: actions/upload-artifact@v4
        with:
          name: conan-cache
          path: ~/.conan/data
